### ISSUE TITLE
Overlapping lines

### ISSUE THREAD

**Issue by kjayhan** [jooyoungseo/jy_CV#10]
Detailed entries for -why- used to look fine, but now they overlap with the following line. I believe this is also the case in your CV's pdf file here: https://github.com/jooyoungseo/jy_CV/blob/master/docs/JooYoung_Seo_CV.pdf

**Comment by jooyoungseo** [comment]
Thanks for reporting. This is an upstream package issue. Please file the issue on [mitchelloharawild/vitae](https://github.com/mitchelloharawild/vitae).

**Comment by kjayhan** [comment]
How did you solve it for your CV? I reported the issue on [mitchelloharawild/vitae](https://github.com/mitchelloharawild/vitae) as well.

**Comment by jooyoungseo** [comment]
1. Delete  `awesome-cv.cls` file in your cloned local directory. Note that this file is not contained in my repo as it is gitignored. Also note that this file extension is `.cls` not `.csl`.

2. Execute `remotes::install_github("mitchelloharawild/vitae")` in R console.

3. Knit `index.Rmd`. This will create a new `.cls` file.

This is what I have done on my end.

**Comment by kjayhan** [comment]
Thank you. I didn't have awesome-cv.cls. That's why I couldn't solve the problem before. Now, I generated awesome-cv.cls by creating a new awesomecv.rmd file, and it works fine now.
