### ISSUE TITLE
Bib item order incorrect

### ISSUE THREAD

**Issue by acircleda** [jooyoungseo/jy_CV#2]
Hi,

I have forked your repo and customized the CV to use my own sections and data. Everything is working well except for the order of some of the items listed in various .bib files.  For several sections, everything is listed in descending order from most recent to oldest except for the last entry, which is out of order from the rest. This has occurred in at least two of my sections.

![image](https://user-images.githubusercontent.com/51770624/82773871-2aec8e00-9e11-11ea-917a-ec754a9217b6.png)

That .bib, created with RefManageR, is:

```
@TechReport{1,
  author = {Melissa Fuesting and Anthony Schmidt},
  title = {Faculty in the health professions: Growth, composition, and salaries},
  year = {2020},
  month = {May},
  institution = {CUPA-HR},
  type = {Research report},
  url = {https://www.cupahr.org/surveys/research-briefs/},
  key = {1},
}

@TechReport{2,
  author = {Adam Pritchard and Sarah Nadel-Hawthorne and Anthony Schmidt and Melissa Fuesting and Jackie Bichsel},
  title = {Administrators in higher education annual report: Key findings, trends, and comprehensive tables for the 2019-20 academic year},
  year = {2020},
  month = {April},
  institution = {CUPA-HR},
  type = {Research report},
  url = {https://www.cupahr.org/surveys/results/},
  key = {2},
}

@TechReport{3,
  author = {Adam Pritchard and Melissa Fuesting and Sarah Nadel-Hawthorne and Anthony Schmidt and Jackie Bichsel},
  title = {Faculty in higher education annual report: Key findings, trends, and comprehensive tables for tenure-track, non-tenure teaching, and non-tenure research faculty; academic department heads; and adjunct faculty for the 2019-20 academic year},
  year = {2020},
  month = {March},
  institution = {CUPA-HR},
  type = {Research report},
  url = {https://www.cupahr.org/surveys/results/},
  key = {3},
}

@TechReport{4,
  author = {Jackie Bichsel and Jasper McChesney and Anthony Schmidt},
  title = {Focus on psychology faculty: Salaries, pay equity, minority representation, and the growth of non-tenure-track faculty},
  year = {2019},
  institution = {CUPA-HR},
  type = {Research report},
  url = {https://www.cupahr.org/surveys/research-briefs/},
  key = {4},
}

@TechReport{5,
  author = {Sarah Nadel and Anthony Schmidt and Jackie Bichesel},
  title = {The impact of the {FSLA} overtime rule on higher education},
  year = {2019},
  institution = {CUPA-HR},
  type = {Research report},
  url = {https://www.cupahr.org/surveys/research-briefs/},
  key = {5},
}

@TechReport{6,
  author = {Anthony Schmidt and Louis Rocconi and Jennifer Ann Morrow and Brenna Berry},
  title = {{College of Architecture and Design’s} undergraduate advising 2019 report},
  year = {2019},
  institution = {{Evaluation, Statistics, and Measurement (ESM) Program Research Group}},
  type = {Research report},
  key = {6},
}

@TechReport{7,
  author = {Jennifer Ann Morrow and Louis Rocconi and Brenna Butler and Anthony Schmidt},
  title = {{University of Tennessee’s} undergraduate advising 2019 evaluation end of year report},
  year = {2019},
  institution = {{Evaluation, Statistics, and Measurement (ESM) Program Research Group}},
  type = {Research report},
  key = {7},
}
```

I have tried changing `sorting` to "", "ydnt", and also "debug" (for sorting by keys), with no effect.
Currently it is:

```
RefManageR::BibOptions(check.entries = FALSE,
           bib.style = "authoryear",
           sorting = "debug",
           cite.style = "alphabetic",
           style = "markdown",
#           hyperlink = FALSE,
           dashed = FALSE)
```

Do you think you can help with this issue?

**Comment by jooyoungseo** [comment]
Thanks for filing the issue. Actually, I forgot to delete the line `RefManageR::BibOptions()` in my `index.Rmd` because I no longer rely on the method for creating my CV. All the bib_entries have been taken care of by [multiple-bibliographies lua filter](https://github.com/pandoc/lua-filters/blob/master/multiple-bibliographies/multiple-bibliographies.lua).

I have not had a chance yet to take a look at your source code to produce your CV; however, if you have just followed my example, you do not need to debug the issue relating to `RefManageR` package. In any event your bib_entry order does not get straightened out, the issue may have to do with either the lua filter or the csl file.

Have you ever used the latest dev version of `vitae` package? Please try with that if you have not yet.

**Comment by acircleda** [comment]
Hi,
I did a little more investigating and the order has something to do with including a month field in the .bib. In the example above, I removed the month field entirely and it fixed the problem. I also had this for one other section (below) and removed the month just for the entry out of order. That fixed it. However, it highlighted another problem. Conferences should be:

Author, A. (**Year, Month**). Title [**Note**]. Location.

I'm not sure the .csl file is printing correct APA 7. I updated the CSL from Zotero (https://www.zotero.org/styles?q=apa) but it did not help.

![image](https://user-images.githubusercontent.com/51770624/82809538-50ea5080-9e5a-11ea-9646-ecf6fe876fbf.png)

I am also testing out the basic `vitae`  templates (dev version), but am having other issues with that too. I used yours because I liked the APA 7 and that it actually knitted correctly!

**Comment by jooyoungseo** [comment]
Hello @acircleda. I am very glad that you have figured out some workarounds!

As per the conference entry, would you mind showing me what your bib entry (the bib file) looks like?

**Comment by acircleda** [comment]
Hi! Thanks for the reply.  I've also reported this as an issue on [`vitae`](https://github.com/mitchelloharawild/vitae/issues/123) with some example images. 

If my .bib file looks like this, the order is fine:

```
@Conference{1,
  author = {Joshua Michael Rosenberg and Lynn Hodge and M Aydeniz and Anthony Schmidt and Alex Lishinski and K Rich and Jennifer Longnecker and Michael Mann and A Sadovnik},
  title = {A survey of teachers and administrators regarding the implementation of new {K-8} computing education standards in {Tennessee}},
  year = {2020},
  organization = {14th Annual Tennessee STEM Education Research Conference, Cookeville, Tennessee},
  note = {Paper presentation},
  booktitle = {conference},
  key = {1},
}

@Conference{2,
  author = {Anthony Schmidt},
  title = {Academic reading circles},
  year = {2016},
  organization = {Southeast TESOL Regional Conference, Louisville, Kentucky},
  note = {Conference session},
  booktitle = {conference},
  key = {2},
}

@Conference{3,
  author = {Anthony Schmidt},
  title = {Principled washback: Integrating test prep to foster academic skills},
  year = {2016},
  organization = {Toronto TESOL Conference, Toronto, Canada},
  note = {Conference session},
  booktitle = {conference},
  key = {3},
}

@Conference{4,
  author = {Anthony Schmidt},
  title = {Academic reading circles and collaborative meaning construction},
  year = {2016},
  organization = {GATESOL IEP Mini-Conference, Atlanta, Georgia},
  note = {Conference session},
  booktitle = {conference},
  key = {4},
}

@Conference{5,
  author = {Anthony Schmidt},
  title = {Audio diaries for improved spoken grammatical accuracy and pronunciation},
  year = {2015},
  organization = {Southeast TESOL Regional Conference, New Orleans, Louisiana.},
  note = {Conference session},
  booktitle = {conference},
  key = {5},
}
```

However, if I add the `month` field (which should be included in APA 7, the order is incorrect and the month is not included:

```
@Conference{1,
  author = {Joshua Michael Rosenberg and Lynn Hodge and M Aydeniz and Anthony Schmidt and Alex Lishinski and K Rich and Jennifer Longnecker and Michael Mann and A Sadovnik},
  title = {A survey of teachers and administrators regarding the implementation of new {K-8} computing education standards in {Tennessee}},
  year = {2020},
  month = {1},
  organization = {14th Annual Tennessee STEM Education Research Conference, Cookeville, Tennessee},
  note = {Paper presentation},
  booktitle = {conference},
  key = {1},
}

@Conference{2,
  author = {Anthony Schmidt},
  title = {Academic reading circles},
  year = {2016},
  month = {10},
  organization = {Southeast TESOL Regional Conference, Louisville, Kentucky},
  note = {Conference session},
  booktitle = {conference},
  key = {2},
}

@Conference{3,
  author = {Anthony Schmidt},
  title = {Principled washback: Integrating test prep to foster academic skills},
  year = {2016},
  month = {5},
  organization = {Toronto TESOL Conference, Toronto, Canada},
  note = {Conference session},
  booktitle = {conference},
  key = {3},
}

@Conference{4,
  author = {Anthony Schmidt},
  title = {Academic reading circles and collaborative meaning construction},
  year = {2016},
  month = {2},
  organization = {GATESOL IEP Mini-Conference, Atlanta, Georgia},
  note = {Conference session},
  booktitle = {conference},
  key = {4},
}

@Conference{5,
  author = {Anthony Schmidt},
  title = {Audio diaries for improved spoken grammatical accuracy and pronunciation},
  year = {2015},
  month = {10},
  organization = {Southeast TESOL Regional Conference, New Orleans, Louisiana.},
  note = {Conference session},
  booktitle = {conference},
  key = {5},
}

```

**Comment by jooyoungseo** [comment]
After few times of my debugging, I would say this has to do with `csl` file. You have to understand `@conference` is one of the `biblatex` entries, not of `bibtex`.

Well, it is sort of tacky and hard to explain, but basically `biblatex` and `bibtex` are different (simply speaking, `bibtex` is old one; `biblatex` is updated one on top of `bibtex`), and `pandoc-citeproc` supports both of them.

On the other hand, typical `csl` (citation style language) files are designed with `bibtex` entries in mind, and that's actually due in part to limited xml tag support.

When people suggest jason conversion from `biblatex`, that's another way of simplifying `biblatex` entries into `bibtex`.

To make the long story short, I know what causes the issue, but I do not have a time to fix that right now.
However, I can give you some hints to get started.

1. If you change your conference bib file like below, you would get the conference list in an ascending order with month info included:

```
@inproceedings{1,
  author = {Joshua Michael Rosenberg and Lynn Hodge and M Aydeniz and Anthony Schmidt and Alex Lishinski and K Rich and Jennifer Longnecker and Michael Mann and A Sadovnik},
  title = {A survey of teachers and administrators regarding the implementation of new {K-8} computing education standards in {Tennessee}},
  date = {2020-01},
  organization = {14th Annual Tennessee STEM Education Research Conference, Cookeville, Tennessee},
  note = {Paper presentation},
  booktitle = {conference},
  key = {1},
}

@inproceedings{2,
  author = {Anthony Schmidt},
  title = {Academic reading circles},
  date = {2016-10},
  organization = {Southeast TESOL Regional Conference, Louisville, Kentucky},
  note = {Conference session},
  booktitle = {conference},
  key = {2},
}

@inproceedings{3,
  author = {Anthony Schmidt},
  title = {Principled washback: Integrating test prep to foster academic skills},
  date = {2016-05},
  organization = {Toronto TESOL Conference, Toronto, Canada},
  note = {Conference session},
  booktitle = {conference},
  key = {3},
}

@inproceedings{4,
  author = {Anthony Schmidt},
  title = {Academic reading circles and collaborative meaning construction},
  date = {2016-02},
  organization = {GATESOL IEP Mini-Conference, Atlanta, Georgia},
  note = {Conference session},
  booktitle = {conference},
  key = {4},
}

@inproceedings{5,
  author = {Anthony Schmidt},
  title = {Audio diaries for improved spoken grammatical accuracy and pronunciation},
  date = {2015-10},
  organization = {Southeast TESOL Regional Conference, New Orleans, Louisiana.},
  note = {Conference session},
  booktitle = {conference},
  key = {5},
}
```

2. In order to make it in a descending order, you will have to make a macro group for conference proceedings in `csl/apa7-cv.csl` file.

It's basically `xml` syntax, so you will get a sense of how to modify this file to meet your needs.

I will revisit this issue later on if I have some time, but I just wanted to give you a starting point.

**Comment by acircleda** [comment]
I tried out your suggestion, with the content of `booktitle` taken from ` organization` and it is formatted more correctly. You are also right that it was not in descending order. After reading through the CSL file, I can say that writing a macro group is beyond my current skills. In fact, this is my first attempt at LaTeX! I appreciate your help.

**Comment by jooyoungseo** [comment]
This issue has been addressed in the latest commits.
